FORMAT: 1A
HOST: http://api.topcoder.com/v2

# TopCoder API
Programmatically access TopCoder challenges and members.

# Group Authorization
Authorization APIs

## Create JWT Token [/auth]
### Create JWT Token [POST]
+ Parameters
    + username (required, string, `heffan`) ... The username
    + password (required, string, `password`) ... The password

+ Response 200 (application/json)

        {
             "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3NtYS5hdXRoMC5jb20vIiwic3ViIjoiYWR8"
        }

+ Response 400 (application/json)

        {
            "name":"Bad Request",
            "value":"400",
            "description":"This message will explain why the request is invalid or cannot be served."
        }

+ Response 404 (application/json)

        {
            "name":"Not Found",
            "value":"404",
            "description":"This message will explain why the URI requested is invalid or the resource does not exist."
        }

+ Response 500 (application/json)

        {
            "name":"Internal Server Error",
            "value":"500",
            "description":"Unknown server error. Please contact support."
        }

+ Response 503 (application/json)

        {
            "name":"Service Unavailable",
            "value":"503",
            "description":"Servers are up but overloaded. Try again later."
        }

## Refresh JWT Token [/reauth]
### Refresh JWT Token [POST]
+ Parameters
    + token (required, string, `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3NtYS5hdXRoMC5jb20vIiwic3ViIjoiYWR8`) ... The old JWT token

+ Response 200 (application/json)

        {
             "token": "DyJCdeAiOiH7V1QiLCJhbGciOiJI5zI1NiJ9.eyJpc3MiOiJodHRrezovL3NtYS5uyXRoMC5jb20vIiwic3ViIoo4XSO2"
        }

+ Response 400 (application/json)

        {
            "name":"Bad Request",
            "value":"400",
            "description":"This message will explain why the request is invalid or cannot be served."
        }

+ Response 404 (application/json)

        {
            "name":"Not Found",
            "value":"404",
            "description":"This message will explain why the URI requested is invalid or the resource does not exist."
        }

+ Response 500 (application/json)

        {
            "name":"Internal Server Error",
            "value":"500",
            "description":"Unknown server error. Please contact support."
        }

+ Response 503 (application/json)

        {
            "name":"Service Unavailable",
            "value":"503",
            "description":"Servers are up but overloaded. Try again later."
        }

## Validate SSO Cookie [/validation/sso]
### Validate SSO Cookie [GET]
+ Parameters
    + Cookie (required, string, `tcsso=132456|4a6acc4d5327773989a7e8c23b04e8cd1c3da79a1256590973ed731ffa0f24a2`) ... The sso cookie

+ Response 200 (application/json)

        {
             "userId": 132456
        }

+ Response 400 (application/json)

        {
            "name":"Bad Request",
            "value":"400",
            "description":"This message will explain why the request is invalid or cannot be served."
        }

+ Response 500 (application/json)

        {
            "name":"Internal Server Error",
            "value":"500",
            "description":"Unknown server error. Please contact support."
        }

+ Response 503 (application/json)

        {
            "name":"Service Unavailable",
            "value":"503",
            "description":"Servers are up but overloaded. Try again later."
        }



# Group User Profile
Register a new user.

## Users [/users]
+ Model (application/json)

        {
            "firstname" : "John",
            "lastname" : "Doe",
            "handle" : "uniqueLogin",
            "country" : "UK",
            "email" : "name@domain.com",
            "password" : "HashedPassword",
            "regSource": "http://registration.source.domain.com",
            "utm_source": "a",
            "utm_medium": "b",
            "utm_campaign": "c"
        }

### Create a new user [POST]
+ Request (application/json)

    [Users][]

+ Response 200 (application/json)

        {
            "name":"OK",
            "value":"200",
            "description":"This message will contain the new user id."
        }

+ Response 400 (application/json)

        {
            "name":"Bad Request",
            "value":"400",
            "description":"This message will explain why the request is invalid or cannot be served."
        }

+ Response 404 (application/json)

        {
            "name":"Not Found",
            "value":"404",
            "description":"This message will explain why the URI requested is invalid or the resource does not exist."
        }

+ Response 422 (application/json)

        {
            "name":"Unprocessable Entity",
            "value":"422",
            "description":"This message will explain why the POST data was not accepted."
        }

+ Response 500 (application/json)

        {
            "name":"Internal Server Error",
            "value":"500",
            "description":"Unknown server error. Please contact support."
        }

+ Response 503 (application/json)

        {
            "name":"Service Unavailable",
            "value":"503",
            "description":"Servers are up but overloaded. Try again later."
        }

### Create a new user via social login [POST]
+ Request (application/json)

        {
            "firstname" : "John",
            "lastname" : "Doe",
            "handle" : "uniqueLogin",
            "country" : "UK",
            "email" : "name@domain.com",
            "socialProvider" : "google",
            "socialUserId": "3003300",
            "socialUserName" : "JohnsGoogleName",
            "socialEmail" : "john@gmail.com",
            "socialEmailVerified" : "true",
            "regSource": "TC API"
        }

+ Response 200 (application/json)

        {
            "name":"OK",
            "value":"200",
            "description":"This message will contain the new user id."
        }

+ Response 400 (application/json)

        {
            "name":"Bad Request",
            "value":"400",
            "description":"This message will explain why the request is invalid or cannot be served."
        }

+ Response 404 (application/json)

        {
            "name":"Not Found",
            "value":"404",
            "description":"This message will explain why the URI requested is invalid or the resource does not exist."
        }

+ Response 422 (application/json)

        {
            "name":"Unprocessable Entity",
            "value":"422",
            "description":"This message will explain why the POST data was not accepted."
        }

+ Response 500 (application/json)

        {
            "name":"Internal Server Error",
            "value":"500",
            "description":"Unknown server error. Please contact support."
        }

+ Response 503 (application/json)

        {
            "name":"Service Unavailable",
            "value":"503",
            "description":"Servers are up but overloaded. Try again later."
        }

## Public Profile [/users/{handle}]
### Public Profile [GET]

+ Parameters
    + handle (required, string, `iRabbit`) ... Member Handle

+ Response 200 (application/json)

        {
             "handle": "hohosky",
             "country": "China",
             "memberSince": "09.28.2005 15:47 EDT",
             "overallEarning": 0,
             "quote": "Focus is a matter of deciding what things you're not going to do.",
             "ratingsSummary": [
                  {
                   "name": "Development",
                   "rating": 1906,
                   "colorStyle": "color: #DDCC00"
                  },
                  {
                   "name": "Design",
                   "rating": 1516,
                   "colorStyle": "color: #DDCC00"
                  },
                  {
                   "name": "Specification",
                   "rating": 1747,
                   "colorStyle": "color: #DDCC00"
                  }
             ],
             "photoLink": "/i/m/hohosky_big.jpg",
             "isCopilot": {
                  "value": true,
                  "software": false,
                  "studio": false
             },
             "isPM": false,
            "Achievements":
            [
                {
                  "date": "03.17.2013 00:00 EDT",
                  "description": "First Forum Post"
                 },
                 {
                  "date": "02.19.2013 00:00 EST",
                  "description": "One Hundred Forum Posts"
                 },
                 {
                  "date": "10.03.2012 00:00 EDT",
                  "description": "First Passing Submission"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "First Successful Challenge"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "Five Rated Algorithm Competitions"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "Five Successful Challenges"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "SRM Winner Div 2"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "Solved Hard Div1 Problem in SRM"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "First Rated Algorithm Competition"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "Solved Hard Div2 Problem in SRM"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "First SRM Room Win (Any Division)"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "Ten Solved Algorithm Problems"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "First Solved Algorithm Problem"
                 },
                 {
                  "date": "09.17.2012 00:00 EDT",
                  "description": "Five Hundred Forum Posts"
                 },
                 {
                  "date": "08.27.2012 00:00 EDT",
                  "description": "First Win"
                 },
                 {
                  "date": "08.27.2012 00:00 EDT",
                  "description": "First Placement"
                 },
                 {
                  "date": "08.20.2012 00:00 EDT",
                  "description": "TopCoder Reviewer"
                 },
                 {
                  "date": "04.10.2012 00:00 EDT",
                  "description": "2012 TopCoder Open Mod Dash Champion"
                 },
                 {
                  "date": "04.07.2012 00:00 EDT",
                  "description": "One Thousand Forum Posts"
                 },
                 {
                  "date": "09.28.2011 00:00 EDT",
                  "description": "2011 TopCoder Open Mod Dash Finalists"
                 },
                 {
                  "date": "10.14.2010 00:00 EDT",
                  "description": "2010 TopCoder Open Mod Dash Finalist"
                 },
                 {
                  "date": "10.21.2005 00:00 EDT",
                  "description": "Twenty Five Placements"
                 }
            ]
        }

+ Response 400 (application/json)

        {
            "name":"Bad Request",
            "value":"400",
            "description":"This message will explain why the request is invalid or cannot be served."
            "details:":"User is not activated."
        }

+ Response 404 (application/json)

        {
            "name":"Not Found",
            "value":"404",
            "description":"This message will explain why the URI requested is invalid or the resource does not exist."
            "details:":"User does not exist."
        }

+ Response 500 (application/json)

        {
            "name":"Internal Server Error",
            "value":"500",
            "description":"Unknown server error. Please contact support."
        }

+ Response 503 (application/json)

        {
            "name":"Service Unavailable",
            "value":"503",
            "description":"Servers are up but overloaded. Try again later."
        }

## My Profile [/user/profile]
### My Profile [GET]
+ Request

    + Headers

            Authorization : Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZHwxMzI0NTYiLCJleHAiOjEzOTI4MTc4ODQsImF1ZCI6InRvcGNvZGVyIiwiaWF0IjoxMzkyNzU3ODg0fQ.7X2IKkiyyI1ExSM5GNpdhJ8fGGK5-oAjzccX6YL_BKY

+ Response 200 (application/json)

        {
             "handle": "hohosky",
             "country": "China",
             "memberSince": "09.28.2005 15:47 EDT",
             "overallEarning": 0,
             "quote": "Focus is a matter of deciding what things you're not going to do.",
             "ratingsSummary": [
                  {
                   "name": "Development",
                   "rating": 1906,
                   "colorStyle": "color: #DDCC00"
                  },
                  {
                   "name": "Design",
                   "rating": 1516,
                   "colorStyle": "color: #DDCC00"
                  },
                  {
                   "name": "Specification",
                   "rating": 1747,
                   "colorStyle": "color: #DDCC00"
                  }
             ],
             "photoLink": "/i/m/hohosky_big.jpg",
             "isCopilot": {
                  "value": true,
                  "software": false,
                  "studio": false
             },
             "isPM": false,
            "Achievements":
            [
                {
                  "date": "03.17.2013 00:00 EDT",
                  "description": "First Forum Post"
                 },
                 {
                  "date": "02.19.2013 00:00 EST",
                  "description": "One Hundred Forum Posts"
                 },
                 {
                  "date": "10.03.2012 00:00 EDT",
                  "description": "First Passing Submission"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "First Successful Challenge"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "Five Rated Algorithm Competitions"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "Five Successful Challenges"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "SRM Winner Div 2"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "Solved Hard Div1 Problem in SRM"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "First Rated Algorithm Competition"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "Solved Hard Div2 Problem in SRM"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "First SRM Room Win (Any Division)"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "Ten Solved Algorithm Problems"
                 },
                 {
                  "date": "09.28.2012 00:00 EDT",
                  "description": "First Solved Algorithm Problem"
                 },
                 {
                  "date": "09.17.2012 00:00 EDT",
                  "description": "Five Hundred Forum Posts"
                 },
                 {
                  "date": "08.27.2012 00:00 EDT",
                  "description": "First Win"
                 },
                 {
                  "date": "08.27.2012 00:00 EDT",
                  "description": "First Placement"
                 },
                 {
                  "date": "08.20.2012 00:00 EDT",
                  "description": "TopCoder Reviewer"
                 },
                 {
                  "date": "04.10.2012 00:00 EDT",
                  "description": "2012 TopCoder Open Mod Dash Champion"
                 },
                 {
                  "date": "04.07.2012 00:00 EDT",
                  "description": "One Thousand Forum Posts"
                 },
                 {
                  "date": "09.28.2011 00:00 EDT",
                  "description": "2011 TopCoder Open Mod Dash Finalists"
                 },
                 {
                  "date": "10.14.2010 00:00 EDT",
                  "description": "2010 TopCoder Open Mod Dash Finalist"
                 },
                 {
                  "date": "10.21.2005 00:00 EDT",
                  "description": "Twenty Five Placements"
                 }
            ],
            "emails": [
            {
                "email": "foo@fooonyou.com",
                "type": "Primary",
                "status": "Active"
            }
            ],
            "name": "firstdok lastdok",
            "address": "address1, city, Maine, 04043, United States",
            "age": "25 - 34",
            "gender": "Male",
            "shirt_size": "Medium",
            "privacy": {
                "showMySchool": "Yes",
                "showMyEarnings": "No",
                "receiveMessages": "Yes",
                "messageBlackList": ["handleA", "handleB"]
             },
             "emailNotification": {
                "competitionAnnouncements": {
                    "algorithmCompetitions": "No",
                    "softwareDevelopmentOpportunities": "Yes",
                    "topCoderStudioCompetitions": "No"
                },
                "others": {
                    "employmentOpportunities": "Yes",
                    "topCoderNewsAndEvents": "Yes",
                    "topCoderDesignStudioNewsletter": "No"
                }
             },
             "demographic": {
                "nonEnglishName": "name1",
                "jobTitle": "Lorem ipsum",
                "company": "company1",
                "country": "Indonesia",
                "representedCountry": "Indonesia",
                "phone": "555555",
                "timeZone": "US/Central",
                "age": "18 - 25",
                "gender": "Male",
                "ethnicBackground": "Asian or Pacific Islander",
                "primaryInterest": "Creative Competition",
                "shirtSize": "Small",
                "collegeMajor": "Computer Science",
                "collegeMajorDescription": "Software Design",
                "degreeProgram": "Bachelors",
                "graduationDate": "21/02/2011",
                "clubsOrOrganizations": "None",
                "school": "Harvard University",
                "gpa": 3.5,
                "gpaScale": 5,
                "isStudent": "Yes",
                "isProfessional": "No"a
             }
        }

+ Response 400 (application/json)

        {
            "name":"Bad Request",
            "value":"400",
            "description":"This message will explain why the request is invalid or cannot be served."
            "details:":"User is not activated."
        }

+ Response 401 (application/json)

        {
            "name":"Unauthorized",
            "value":"401",
            "description":"This message will explain why the request is invalid or cannot be served."
            "details:":"Authentication credential was missing."
        }

+ Response 500 (application/json)

        {
            "name":"Internal Server Error",
            "value":"500",
            "description":"Unknown server error. Please contact support."
        }

+ Response 503 (application/json)

        {
            "name":"Service Unavailable",
            "value":"503",
            "description":"Servers are up but overloaded. Try again later."
        }

## My Profile [/user/profile]
### My Profile [POST]
+ Request

    + Headers

            Authorization : Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZHwxMzI0NTYiLCJleHAiOjEzOTI4MTc4ODQsImF1ZCI6InRvcGNvZGVyIiwiaWF0IjoxMzkyNzU3ODg0fQ.7X2IKkiyyI1ExSM5GNpdhJ8fGGK5-oAjzccX6YL_BKY

+ Response 200 (application/json)

        {
        }

+ Response 400 (application/json)

        {
            "name":"Bad Request",
            "value":"400",
            "description":"This message will explain why the request is invalid or cannot be served."
            "details:":"User is not activated."
        }

+ Response 401 (application/json)

        {
            "name":"Unauthorized",
            "value":"401",
            "description":"This message will explain why the request is invalid or cannot be served."
            "details:":"Authentication credential was missing."
        }

+ Response 500 (application/json)

        {
            "name":"Internal Server Error",
            "value":"500",
            "description":"Unknown server error. Please contact support."
        }

+ Response 503 (application/json)

        {
            "name":"Service Unavailable",
            "value":"503",
            "description":"Servers are up but overloaded. Try again later."
        }

## My Profile [/user/activation-email]
### My Profile [GET]
+ Request

    + Headers

            Authorization : Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZHwxMzI0NTYiLCJleHAiOjEzOTI4MTc4ODQsImF1ZCI6InRvcGNvZGVyIiwiaWF0IjoxMzkyNzU3ODg0fQ.7X2IKkiyyI1ExSM5GNpdhJ8fGGK5-oAjzccX6YL_BKY

+ Response 200 (application/json)

        {
            success: true
        }

+ Response 400 (application/json)

        {
            "name":"Bad Request",
            "value":"400",
            "description":"This message will explain why the request is invalid or cannot be served."
            "details:":"You're already activated."
        }

+ Response 400 (application/json)

        {
            "name":"Bad Request",
            "value":"400",
            "description":"This message will explain why the request is invalid or cannot be served."
            "details:":"Sorry, you already reached the limit of resend times. Please contact for support."
        }

+ Response 401 (application/json)

        {
            "name":"Unauthorized",
            "value":"401",
            "description":"This message will explain why the request is invalid or cannot be served."
            "details:":"You must login for this endpoint."
        }

+ Response 500 (application/json)

        {
            "name":"Internal Server Error",
            "value":"500",
            "description":"Unknown server error. Please contact support."
        }

+ Response 503 (application/json)

        {
            "name":"Service Unavailable",
            "value":"503",
            "description":"Servers are up but overloaded. Try again later."
        }
